// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

window.Hand = (function(superClass) {
  extend(Hand, superClass);

  function Hand() {
    return Hand.__super__.constructor.apply(this, arguments);
  }

  Hand.prototype.model = Card;

  Hand.prototype.initialize = function(array, deck, isDealer) {
    this.deck = deck;
    this.isDealer = isDealer;
  };

  Hand.prototype.hit = function() {
    var lastCard;
    lastCard = this.deck.pop();
    this.add(lastCard);
    this.bust();
    this.blackJack();
    return lastCard;
  };

  Hand.prototype.hasAce = function() {
    return this.reduce(function(memo, card) {
      return memo || card.get('value') === 1;
    }, 0);
  };

  Hand.prototype.minScore = function() {
    return this.reduce(function(score, card) {
      return score + (card.get('revealed') ? card.get('value') : 0);
    }, 0);
  };

  Hand.prototype.scores = function() {
    return [this.minScore(), this.minScore() + 10 * this.hasAce()];
  };

  Hand.prototype.bust = function() {
    if (this.minScore() > 21) {
      this.trigger('over');
    }
  };

  Hand.prototype.blackJack = function() {
    if (this.minScore() === 21) {
      return this.trigger('over');
    }
  };

  Hand.prototype.reveal = function() {
    return _.each(this.models, function(card) {
      return card.set('revealed', true);
    });
  };

  return Hand;

})(Backbone.Collection);
