// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

window.AppView = (function(superClass) {
  extend(AppView, superClass);

  function AppView() {
    return AppView.__super__.constructor.apply(this, arguments);
  }

  AppView.prototype.template = _.template('<button class="hit-button">Hit</button> <button class="stand-button">Stand</button> <button class="dealAgain">Deal Again</button> <div class="player-hand-container"></div> <div class="dealer-hand-container"></div> <div class="game-result"></div>');

  AppView.prototype.events = {
    'click .hit-button': function() {
      return this.model.get('playerHand').hit();
    },
    'click .stand-button': function() {
      return this.model.stand();
    },
    'click .dealAgain': function() {
      return this.model.initialize();
    },
    'click .split-button': function() {
      return this.model.get('playerHand').split();
    },
    'click .double-button': function() {
      return this.model.get('playerHand').double();
    }
  };

  AppView.prototype.initialize = function() {
    this.render();
    this.model.on('dealAgain', this.render, this);
    return this.model.on('gameOver', this.restart);
  };

  AppView.prototype.render = function() {
    this.$el.children().detach();
    this.$el.html(this.template());
    this.$('.player-hand-container').html(new HandView({
      collection: this.model.get('playerHand')
    }).el);
    this.$('.dealer-hand-container').html(new HandView({
      collection: this.model.get('dealerHand')
    }).el);
    $(".hit-button").show();
    $(".stand-button").show();
    $(".dealAgain").hide();
    return $(".game-result").hide();
  };

  AppView.prototype.restart = function() {
    $(".dealAgain").show();
    $(".hit-button").hide();
    $(".stand-button").hide();
    return $(".game-result").text(this.get('gameResult')).show();
  };

  return AppView;

})(Backbone.View);
