// Generated by CoffeeScript 1.10.0
var assert;

assert = chai.assert;

describe("Blackjack View", function() {
  it("should always pass...", function() {
    return assert.strictEqual(true, true);
  });
  return it("should add a card to playerHand when player hits", function() {});
});
