// Generated by CoffeeScript 1.10.0
var assert;

assert = chai.assert;

describe('HandView', function() {
  var deck, hand;
  deck = null;
  hand = null;
  beforeEach(function() {
    deck = new Deck();
    hand = deck.dealPlayer();
  });
  describe('hit', function() {
    it('should give the last card from the deck', function() {
      assert.strictEqual(deck.length, 50);
      assert.strictEqual(deck.last(), hand.hit());
      assert.strictEqual(deck.length, 49);
    });
  });
  describe('stand', function() {
    return it('should not do anything', function() {
      assert.strictEqual();
    });
  });
  return describe('relationship', function() {
    it('hand should be an instance of deck', function() {
      assert.strictEqual(hand).to.be.an.instanceOf(deck);
    });
  });
});
